Python3: fix rexec error while calling self.process.stdin.write
While running nfstest_delegation of nfstest in v3.0:

  $ ./nfstest_delegation --nfsversion=4.2 -e /nfsroot \
      --server 192.168.220.184 --client 192.168.220.107
  Traceback (most recent call last):
    File "./nfstest_delegation", line 1666, in <module>
      x = DelegTest(usage=USAGE, testnames=TESTNAMES, testgroups=TESTGROUPS, sid=SCRIPT_ID)
    File "./nfstest_delegation", line 363, in __init__
      self.create_rexec(client_name)
    File "/root/nfstest/nfstest/test_util.py", line 1370, in create_rexec
      self.rexecobj = Rexec(servername, **kwds)
    File "/root/nfstest/nfstest/rexec.py", line 295, in __init__
      self.process.stdin.write(server_code)
  TypeError: a bytes-like object is required, not 'str'

In python3, self.process.stdin.write() only accepts a bytes-like
object not 'str'.
Fix it by calling server_code.encode() and self.process.stdin.flush().

Signed-off-by: Su Yue <suy.fnst@fujitsu.com>